### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by dtorres** [marcgreenstock/douche#1]
i need a SOAP client, yours seemed nice enough but i've tried the test you provide with http://soap.amazon.com/schemas3/AmazonWebServices.wsdl and node returns

/usr/local/lib/node_modules/douche/lib/douche/wsdl.js:74
  attrs.forEach(function(url,index) {
        ^
TypeError: Object #<Object> has no method 'forEach'
    at [object Object]._read_namespaces (/usr/local/lib/node_modules/douche/lib/douche/wsdl.js:74:9)
    at /usr/local/lib/node_modules/douche/lib/douche/wsdl.js:20:10
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/douche/lib/douche/wsdl.js:102:7)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1226:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

How can I fix this? should I use a specific nodejs version (i have the latest) or i'm missing something?

**Comment by marcgreenstock** [comment]
Hey waroface, I've abandoned this project for now. I wrote this because no other soap library existed yet but before i finished https://github.com/milewise/node-soap was published. It's far more stable.

**Comment by 0x80** [comment]
Hi Marc, 

Maybe you could make this a bit more clear somewhere. It could have saved me a few hours trying to get this to work.
